"project_id": "477497"
"api_token_env": "CROWDIN_TOKEN"
"base_path": "common/src/main/resources/assets/betterf3/lang"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "en_us.json",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "%two_letters_code%.json",

  skip_untranslated_files: false


 }
]
