name: Crowdin Tasks

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
    #        │ │ │ │ │                                   7 is also Sunday on some systems)
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:
  crowdin-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Run Crowdin Action
        uses: crowdin/github-action@1.4.13
        with:
            upload_sources: true
            upload_translations: false

            download_translations: true
            skip_untranslated_files: false
            skip_untranslated_strings: false
            commit_message: "Update Translations from Crowdin"

            localization_branch_name: "l10n/${{ github.ref_name }}"
            create_pull_request: true
            pull_request_title: "Update Translations from Crowdin"
            pull_request_labels: "l10n"
            pull_request_base_branch_name: ${{ github.ref_name }}

            config: crowdin.yml
        env:
            CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
            CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
